'use client';

import { useState } from 'react';
import type { AnalysisResult } from '@shared/types';
import styles from './ShareReport.module.css';

interface ShareReportProps {
  result: AnalysisResult;
}

function generateTextReport(result: AnalysisResult): string {
  const lines: string[] = [];
  const divider = '━'.repeat(48);

  lines.push('🛡️ SOLANA SCAM DETECTOR — RISK REPORT');
  lines.push(divider);
  lines.push('');
  lines.push(`📍 Address: ${result.address}`);
  lines.push(`📋 Type: ${result.mode === 'token' ? 'Token' : 'Wallet'}`);
  lines.push(`📅 Analyzed: ${new Date(result.analyzedAt).toLocaleString()}`);
  lines.push('');
  lines.push(divider);
  lines.push(`⚡ OVERALL RISK SCORE: ${result.overallScore}/100 (${result.overallLevel.toUpperCase()})`);
  lines.push(divider);
  lines.push('');
  lines.push(result.summary);
  lines.push('');

  // Category breakdown
  const categories = [
    { key: 'rugPull' as const, icon: '💣' },
    { key: 'fakeVolume' as const, icon: '📊' },
    { key: 'suspiciousWallet' as const, icon: '👤' },
    { key: 'lpHealth' as const, icon: '🔗' },
    { key: 'clusterRisk' as const, icon: '🕸️' },
  ];

  for (const cat of categories) {
    const data = result.categories[cat.key];
    lines.push(`${cat.icon} ${data.name}: ${data.score}/100 (${data.level.toUpperCase()})`);
    for (const signal of data.signals) {
      const prefix = signal.severity === 'high' ? '  🔴' : signal.severity === 'medium' ? '  🟡' : '  🟢';
      lines.push(`${prefix} ${signal.label}${signal.value ? ` — ${signal.value}` : ''}`);
    }
    lines.push('');
  }

  // Token metadata if available
  if (result.tokenInfo) {
    lines.push('🪙 TOKEN METADATA');
    lines.push(`  Supply: ${formatSupply(result.tokenInfo.supply)}`);
    lines.push(`  Mint Authority: ${result.tokenInfo.mintAuthorityRevoked ? 'Revoked ✓' : 'Active ⚠️'}`);
    lines.push(`  Freeze Authority: ${result.tokenInfo.freezeAuthorityRevoked ? 'Revoked ✓' : 'Active ⚠️'}`);
    lines.push('');
  }

  if (result.walletInfo) {
    lines.push('👛 WALLET INFO');
    lines.push(`  Balance: ${result.walletInfo.balanceSOL.toFixed(4)} SOL`);
    lines.push(`  Token Holdings: ${result.walletInfo.tokenCount}`);
    lines.push(`  Recent Txs: ${result.walletInfo.transactionCount}`);
    lines.push('');
  }

  // ML Analysis
  if (result.mlInsight?.modelAvailable) {
    lines.push('🤖 ML ANALYSIS');
    lines.push(`  Scam Probability: ${result.mlInsight.scamProbability}%`);
    lines.push(`  Anomaly Score: ${result.mlInsight.anomalyScore}%`);
    lines.push(`  Model Confidence: ${Math.round(result.mlInsight.confidence * 100)}%`);
    if (result.mlInsight.topFeatures.length > 0) {
      lines.push('  Top Factors:');
      for (const f of result.mlInsight.topFeatures) {
        lines.push(`    • ${f.name}: ${f.contribution}%`);
      }
    }
    lines.push('');
  }

  if (result.confidence !== undefined) {
    lines.push(`📊 Data Quality: ${Math.round(result.confidence * 100)}%`);
    lines.push('');
  }

  lines.push(divider);
  lines.push(`🔗 Solscan: https://solscan.io/${result.mode === 'token' ? 'token' : 'account'}/${result.address}`);
  lines.push('');
  lines.push('⚠️ This is a heuristic-based analysis. Not financial advice.');
  lines.push('   Generated by Solana Scam Detector');

  return lines.join('\n');
}

function formatSupply(supply: number): string {
  if (supply >= 1e12) return `${(supply / 1e12).toFixed(2)}T`;
  if (supply >= 1e9) return `${(supply / 1e9).toFixed(2)}B`;
  if (supply >= 1e6) return `${(supply / 1e6).toFixed(2)}M`;
  if (supply >= 1e3) return `${(supply / 1e3).toFixed(2)}K`;
  return supply.toFixed(2);
}

export default function ShareReport({ result }: ShareReportProps) {
  const [showPreview, setShowPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const report = generateTextReport(result);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* ignore */
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Risk Report: ${result.address.slice(0, 8)}...`,
          text: report,
        });
      } catch {
        // User cancelled or share failed — fall back to copy
        handleCopy();
      }
    } else {
      handleCopy();
    }
  };

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `risk-report-${result.address.slice(0, 8)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className={styles.container}>
      <div className={styles.actions}>
        <button className={styles.shareBtn} onClick={handleShare} title="Share report">
          📤 Share
        </button>
        <button className={styles.copyBtn} onClick={handleCopy} title="Copy report to clipboard">
          {copied ? '✅ Copied!' : '📋 Copy Report'}
        </button>
        <button className={styles.downloadBtn} onClick={handleDownload} title="Download as text file">
          💾 Download
        </button>
        <button
          className={`${styles.previewBtn} ${showPreview ? styles.previewBtnActive : ''}`}
          onClick={() => setShowPreview(!showPreview)}
        >
          {showPreview ? '▲ Hide Preview' : '▼ Preview'}
        </button>
      </div>

      {showPreview && (
        <pre className={styles.preview}>{report}</pre>
      )}
    </div>
  );
}
